name: manual-ci

on:
  pull_request:
    types: [ labeled ]

jobs:
  test:
    if: ${{ github.event.label.name == 'run-test' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo test
